/**
 * @file qiconFromTheme.h
 *
 * @author Dan Keenan
 * @date 9/28/25
 * @copyright GNU GPLv3
 */

#ifndef SRC_PATCHMAN_QICONFROMTHEME_H
#define SRC_PATCHMAN_QICONFROMTHEME_H

#include <QIcon>

namespace patchman {
#if QT_VERSION < QT_VERSION_CHECK(6, 7, 0)
/** Emulate QIcon::ThemeIcon */
enum class ThemeIcon {
    AddressBookNew,
    ApplicationExit,
    AppointmentNew,
    CallStart,
    CallStop,
    ContactNew,
    DocumentNew,
    DocumentOpen,
    DocumentOpenRecent,
    DocumentPageSetup,
    DocumentPrint,
    DocumentPrintPreview,
    DocumentProperties,
    DocumentRevert,
    DocumentSave,
    DocumentSaveAs,
    DocumentSend,
    EditClear,
    EditCopy,
    EditCut,
    EditDelete,
    EditFind,
    EditPaste,
    EditRedo,
    EditSelectAll,
    EditUndo,
    FolderNew,
    FormatIndentLess,
    FormatIndentMore,
    FormatJustifyCenter,
    FormatJustifyFill,
    FormatJustifyLeft,
    FormatJustifyRight,
    FormatTextDirectionLtr,
    FormatTextDirectionRtl,
    FormatTextBold,
    FormatTextItalic,
    FormatTextUnderline,
    FormatTextStrikethrough,
    GoDown,
    GoHome,
    GoNext,
    GoPrevious,
    GoUp,
    HelpAbout,
    HelpFaq,
    InsertImage,
    InsertLink,
    InsertText,
    ListAdd,
    ListRemove,
    MailForward,
    MailMarkImportant,
    MailMarkRead,
    MailMarkUnread,
    MailMessageNew,
    MailReplyAll,
    MailReplySender,
    MailSend,
    MediaEject,
    MediaPlaybackPause,
    MediaPlaybackStart,
    MediaPlaybackStop,
    MediaRecord,
    MediaSeekBackward,
    MediaSeekForward,
    MediaSkipBackward,
    MediaSkipForward,
    ObjectRotateLeft,
    ObjectRotateRight,
    ProcessStop,
    SystemLockScreen,
    SystemLogOut,
    SystemSearch,
    SystemReboot,
    SystemShutdown,
    ToolsCheckSpelling,
    ViewFullscreen,
    ViewRefresh,
    ViewRestore,
    WindowClose,
    WindowNew,
    ZoomFitBest,
    ZoomIn,
    ZoomOut,

    AudioCard,
    AudioInputMicrophone,
    Battery,
    CameraPhoto,
    CameraVideo,
    CameraWeb,
    Computer,
    DriveHarddisk,
    DriveOptical,
    InputGaming,
    InputKeyboard,
    InputMouse,
    InputTablet,
    MediaFlash,
    MediaOptical,
    MediaTape,
    MultimediaPlayer,
    NetworkWired,
    NetworkWireless,
    Phone,
    Printer,
    Scanner,
    VideoDisplay,

    AppointmentMissed,
    AppointmentSoon,
    AudioVolumeHigh,
    AudioVolumeLow,
    AudioVolumeMedium,
    AudioVolumeMuted,
    BatteryCaution,
    BatteryLow,
    DialogError,
    DialogInformation,
    DialogPassword,
    DialogQuestion,
    DialogWarning,
    FolderDragAccept,
    FolderOpen,
    FolderVisiting,
    ImageLoading,
    ImageMissing,
    MailAttachment,
    MailUnread,
    MailRead,
    MailReplied,
    MediaPlaylistRepeat,
    MediaPlaylistShuffle,
    NetworkOffline,
    PrinterPrinting,
    SecurityHigh,
    SecurityLow,
    SoftwareUpdateAvailable,
    SoftwareUpdateUrgent,
    SyncError,
    SyncSynchronizing,
    UserAvailable,
    UserOffline,
    WeatherClear,
    WeatherClearNight,
    WeatherFewClouds,
    WeatherFewCloudsNight,
    WeatherFog,
    WeatherShowers,
    WeatherSnow,
    WeatherStorm,
};
#else
using ThemeIcon = QIcon::ThemeIcon;
#endif
QIcon qiconFromTheme(ThemeIcon iconName);
} // namespace patchman

#endif //SRC_PATCHMAN_QICONFROMTHEME_H
